name: liquibase-octopus-pipeline
on: push
jobs:
  zipTheArtefacts:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v2
      - name: Check the directory
        run: |
          pwd
          ls -ll
