name: liquibase-octopus-pipeline
on: push
jobs:
  zipTheArtefacts:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v2
      - name: Zip the Liquibase Folder
        uses: montudor/action-zip@v1
        with:
          args: zip -qq -r dir.zip LiquibaseTest
      - name: Check the directory
        run: |
          pwd
          ls -ll
