name: liquibase-octopus-pipeline
on: push
jobs:
  zipTheArtefacts:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v2

      - name: Echo current date
        run: echo ${{ github.event.repository.updated_at}}
      - name: Zip the Liquibase Folder
        uses: montudor/action-zip@v1
        with:
          args: zip -qq -r  Escapia_Liquibase_${{ github.ref_name }}_${{ github.event.repository.updated_at}}.zip LiquibaseTest
      - name: Check the directory
        run: |
          pwd
          ls -ll
