name: liquibase-octopus-pipeline
on: push
jobs:
  zipTheArtefacts:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v2

      - name: Echo current date
        run: echo ${{ github.event.repository.updated_at}}
      - name: Zip the Liquibase Folder
        uses: montudor/action-zip@v1
        with:
          args: zip -qq -r  Escapia_Liquibase_${{ github.ref_name }}_${{ github.event.repository.updated_at}}.zip Liquibase
  pushArtefact:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v2

      - name: Connecting to JFrog
        run: echo "Connecting to JFrog"
  deployToOctopus:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v2

      - name: Deploying to Octopus
        run: echo "Deploying to Octopus"

