name: liquibase-octopus-pipeline
on: push
jobs:
  zipTheArtefacts:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v2
      - name: Set current date as env variable
        run: echo "NOW::$(date +'%Y-%m-%dT%H:%M:%S')" >> $GITHUB_ENV
      - name: Echo current date
        run: echo $NOW
      - name: Zip the Liquibase Folder
        uses: montudor/action-zip@v1
        with:
          args: zip -qq -r  Escapia_Liquibase_${{ github.ref_name }}_dir.zip LiquibaseTest
      - name: Check the directory
        run: |
          pwd
          ls -ll
